version: "3.9"

services:
  backend:
    build:
      context: ./fastapi-backend
      dockerfile: Dockerfile
    container_name: salary_loan_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./streamlit-frontend
      dockerfile: Dockerfile
    container_name: salary_loan_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
